### ISSUE TITLE
Do not define unprefixed faces

### ISSUE THREAD

**Issue by dgutov** [tmalsburg/tango-plus-theme#7]
Such as `quote` and `deemphasized`.

Just looking at their names, they seem like faces from the core set. That led me to making a mistake of using one of them in public code, which in turn triggered errors for people who don't have `tango-plus` installed and enabled.

**Comment by tmalsburg** [comment]
Thanks.  Makes sense.  Will change it.

**Comment by tmalsburg** [comment]
Done. See f31d282.

**Comment by dgutov** [comment]
Thanks!
